//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amuse.App.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Amuse.App.Resources.AppErrors", typeof(AppErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute Automation.
        /// </summary>
        public static string ExecuteAutomationTitle {
            get {
                return ResourceManager.GetString("ExecuteAutomationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute Pipeline.
        /// </summary>
        public static string ExecutePipelineTitle {
            get {
                return ResourceManager.GetString("ExecutePipelineTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated audio result not found..
        /// </summary>
        public static string GeneratedAudioNotFound {
            get {
                return ResourceManager.GetString("GeneratedAudioNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated image result not found..
        /// </summary>
        public static string GeneratedImageNotFound {
            get {
                return ResourceManager.GetString("GeneratedImageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated text result not found..
        /// </summary>
        public static string GeneratedTextNotFound {
            get {
                return ResourceManager.GetString("GeneratedTextNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated video result not found..
        /// </summary>
        public static string GeneratedVideoNotFound {
            get {
                return ResourceManager.GetString("GeneratedVideoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import component file..
        /// </summary>
        public static string ImportComponent {
            get {
                return ResourceManager.GetString("ImportComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import Environment file..
        /// </summary>
        public static string ImportEnvironment {
            get {
                return ResourceManager.GetString("ImportEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Error.
        /// </summary>
        public static string ImportErrorTitle {
            get {
                return ResourceManager.GetString("ImportErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import model file..
        /// </summary>
        public static string ImportModel {
            get {
                return ResourceManager.GetString("ImportModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Pipeline.
        /// </summary>
        public static string LoadPipelineTitle {
            get {
                return ResourceManager.GetString("LoadPipelineTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse document..
        /// </summary>
        public static string ParseErrorDocument {
            get {
                return ResourceManager.GetString("ParseErrorDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse Error.
        /// </summary>
        public static string ParseErrorTitle {
            get {
                return ResourceManager.GetString("ParseErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipeline Closed Unexpectedly.
        /// </summary>
        public static string PipelineClosedUnexpectedly {
            get {
                return ResourceManager.GetString("PipelineClosedUnexpectedly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred.
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Error.
        /// </summary>
        public static string UnexpectedErrorTitle {
            get {
                return ResourceManager.GetString("UnexpectedErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unload Pipeline.
        /// </summary>
        public static string UnloadPipelineTitle {
            get {
                return ResourceManager.GetString("UnloadPipelineTitle", resourceCulture);
            }
        }
    }
}
