//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amuse.App.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppToolTips {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppToolTips() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Amuse.App.Resources.AppToolTips", typeof(AppToolTips).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gated Model - Civitai Authentication Required..
        /// </summary>
        public static string ToolTip_Acsess_Civitai {
            get {
                return ResourceManager.GetString("ToolTip_Acsess_Civitai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gated Model - HuggingFace Authentication Required..
        /// </summary>
        public static string ToolTip_Acsess_HuggingFace {
            get {
                return ResourceManager.GetString("ToolTip_Acsess_HuggingFace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immediately stops generation by closing the backend process..
        /// </summary>
        public static string ToolTip_GenerateStop {
            get {
                return ResourceManager.GetString("ToolTip_GenerateStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add LoRA Trigger word.
        /// </summary>
        public static string ToolTip_Lora_AddTrigger {
            get {
                return ResourceManager.GetString("ToolTip_Lora_AddTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available For Download.
        /// </summary>
        public static string ToolTip_ModelStatus_Available {
            get {
                return ResourceManager.GetString("ToolTip_ModelStatus_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Download Failed.
        /// </summary>
        public static string ToolTip_ModelStatus_DownloadFailed {
            get {
                return ResourceManager.GetString("ToolTip_ModelStatus_DownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Downloading.
        /// </summary>
        public static string ToolTip_ModelStatus_Downloading {
            get {
                return ResourceManager.GetString("ToolTip_ModelStatus_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Download Queued.
        /// </summary>
        public static string ToolTip_ModelStatus_DownloadQueue {
            get {
                return ResourceManager.GetString("ToolTip_ModelStatus_DownloadQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Installed.
        /// </summary>
        public static string ToolTip_ModelStatus_Installed {
            get {
                return ResourceManager.GetString("ToolTip_ModelStatus_Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Not Installed.
        /// </summary>
        public static string ToolTip_ModelStatus_NotInstalled {
            get {
                return ResourceManager.GetString("ToolTip_ModelStatus_NotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Update Required.
        /// </summary>
        public static string ToolTip_ModelStatus_Unknown {
            get {
                return ResourceManager.GetString("ToolTip_ModelStatus_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Generation.
        /// </summary>
        public static string ToolTip_Paint_Cancel {
            get {
                return ResourceManager.GetString("ToolTip_Paint_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Drawing.
        /// </summary>
        public static string ToolTip_Paint_ClearDraw {
            get {
                return ResourceManager.GetString("ToolTip_Paint_ClearDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eraser.
        /// </summary>
        public static string ToolTip_Paint_Eraser {
            get {
                return ResourceManager.GetString("ToolTip_Paint_Eraser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill Background.
        /// </summary>
        public static string ToolTip_Paint_FillBG {
            get {
                return ResourceManager.GetString("ToolTip_Paint_FillBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit to curve.
        /// </summary>
        public static string ToolTip_Paint_FitCurve {
            get {
                return ResourceManager.GetString("ToolTip_Paint_FitCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlighter Pen.
        /// </summary>
        public static string ToolTip_Paint_Highlighter {
            get {
                return ResourceManager.GetString("ToolTip_Paint_Highlighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Generation.
        /// </summary>
        public static string ToolTip_Paint_Live {
            get {
                return ResourceManager.GetString("ToolTip_Paint_Live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Image Background.
        /// </summary>
        public static string ToolTip_Paint_LoadImageBG {
            get {
                return ResourceManager.GetString("ToolTip_Paint_LoadImageBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round Paint Brush.
        /// </summary>
        public static string ToolTip_Paint_RoundBrush {
            get {
                return ResourceManager.GetString("ToolTip_Paint_RoundBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square Paint Brush.
        /// </summary>
        public static string ToolTip_Paint_SquareBrush {
            get {
                return ResourceManager.GetString("ToolTip_Paint_SquareBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable stylus pressure support.
        /// </summary>
        public static string ToolTip_Paint_Stylus {
            get {
                return ResourceManager.GetString("ToolTip_Paint_Stylus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Seed.
        /// </summary>
        public static string ToolTip_Seed_New {
            get {
                return ResourceManager.GetString("ToolTip_Seed_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Seeds.
        /// </summary>
        public static string ToolTip_Seed_Random {
            get {
                return ResourceManager.GetString("ToolTip_Seed_Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Conversation.
        /// </summary>
        public static string ToolTip_Text_Branch {
            get {
                return ResourceManager.GetString("ToolTip_Text_Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Text.
        /// </summary>
        public static string ToolTip_Text_Clear {
            get {
                return ResourceManager.GetString("ToolTip_Text_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Response Html.
        /// </summary>
        public static string ToolTip_Text_CopyResponseHtml {
            get {
                return ResourceManager.GetString("ToolTip_Text_CopyResponseHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Response Text.
        /// </summary>
        public static string ToolTip_Text_CopyResponseText {
            get {
                return ResourceManager.GetString("ToolTip_Text_CopyResponseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Result Formatting.
        /// </summary>
        public static string ToolTip_Text_FormatDisable {
            get {
                return ResourceManager.GetString("ToolTip_Text_FormatDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Result Formatting (experimental).
        /// </summary>
        public static string ToolTip_Text_FormatEnable {
            get {
                return ResourceManager.GetString("ToolTip_Text_FormatEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rewind Last Message.
        /// </summary>
        public static string ToolTip_Text_Rewind {
            get {
                return ResourceManager.GetString("ToolTip_Text_Rewind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Response To File.
        /// </summary>
        public static string ToolTip_Text_SaveResponseFile {
            get {
                return ResourceManager.GetString("ToolTip_Text_SaveResponseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Streaming Token Updates.
        /// </summary>
        public static string ToolTip_Text_StreamDisable {
            get {
                return ResourceManager.GetString("ToolTip_Text_StreamDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Streaming Token Updates.
        /// </summary>
        public static string ToolTip_Text_StreamEnable {
            get {
                return ResourceManager.GetString("ToolTip_Text_StreamEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Thinking Content.
        /// </summary>
        public static string ToolTip_Text_ThinkingHide {
            get {
                return ResourceManager.GetString("ToolTip_Text_ThinkingHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Thinking Content.
        /// </summary>
        public static string ToolTip_Text_ThinkingShow {
            get {
                return ResourceManager.GetString("ToolTip_Text_ThinkingShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Timeline.
        /// </summary>
        public static string ToolTip_VideoTimeline_Clear {
            get {
                return ResourceManager.GetString("ToolTip_VideoTimeline_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extend Timeline.
        /// </summary>
        public static string ToolTip_VideoTimeline_Extend {
            get {
                return ResourceManager.GetString("ToolTip_VideoTimeline_Extend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Selected Frames(s).
        /// </summary>
        public static string ToolTip_VideoTimeline_FrameRemove {
            get {
                return ResourceManager.GetString("ToolTip_VideoTimeline_FrameRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Selected Frame To History.
        /// </summary>
        public static string ToolTip_VideoTimeline_FrameSave {
            get {
                return ResourceManager.GetString("ToolTip_VideoTimeline_FrameSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Video.
        /// </summary>
        public static string ToolTip_VideoTimeline_Save {
            get {
                return ResourceManager.GetString("ToolTip_VideoTimeline_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Segment.
        /// </summary>
        public static string ToolTip_VideoTimeline_SegmentCopy {
            get {
                return ResourceManager.GetString("ToolTip_VideoTimeline_SegmentCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Segment Down.
        /// </summary>
        public static string ToolTip_VideoTimeline_SegmentDown {
            get {
                return ResourceManager.GetString("ToolTip_VideoTimeline_SegmentDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Segment.
        /// </summary>
        public static string ToolTip_VideoTimeline_SegmentRemove {
            get {
                return ResourceManager.GetString("ToolTip_VideoTimeline_SegmentRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split Segment.
        /// </summary>
        public static string ToolTip_VideoTimeline_SegmentSplit {
            get {
                return ResourceManager.GetString("ToolTip_VideoTimeline_SegmentSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Segment Up.
        /// </summary>
        public static string ToolTip_VideoTimeline_SegmentUp {
            get {
                return ResourceManager.GetString("ToolTip_VideoTimeline_SegmentUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trim Timeline.
        /// </summary>
        public static string ToolTip_VideoTimeline_Trim {
            get {
                return ResourceManager.GetString("ToolTip_VideoTimeline_Trim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom In.
        /// </summary>
        public static string ToolTip_VideoTimeline_ZoomIn {
            get {
                return ResourceManager.GetString("ToolTip_VideoTimeline_ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Out.
        /// </summary>
        public static string ToolTip_VideoTimeline_ZoomOut {
            get {
                return ResourceManager.GetString("ToolTip_VideoTimeline_ZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Memory Modes.
        /// </summary>
        public static string ToolTop_MemoryEstimate {
            get {
                return ResourceManager.GetString("ToolTop_MemoryEstimate", resourceCulture);
            }
        }
    }
}
